version: '2'

services: 
 cas1: 
    container_name: cas1
    image: bitnami/cassandra:latest
    volumes:
      - ./storage/node1:/var/lib/cassandra/data
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=SeedsCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DATACENTER=datacenter1
 cas2:
  container_name: cas2
  image: bitnami/cassandra:latest
  volumes:
      - ./storage/node2:/var/lib/cassandra/data
  ports:
      - 9043:9042
  depends_on:
    - cas1
  environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=SeedsCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_SEEDS=cas1
