name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Pull with compose
        run: docker-compose pull
      -
        name: Run database
        run: docker-compose up -f database/docker-compose.yml -d
      -
        name: Sleep for 60 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      -
        name: Run tests
        run: docker-compose up --abort-on-container-exit
        env:
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          PGP_PUBLIC_KEY: ${{ secrets.PGP_PUBLIC_KEY }}
